%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\terry\OneDrive\PhD\Xe Model 2019-1-03\run_10_SA\New_Xe_Model\Buildup_Trans_ORNL_TM_3464_Fig_26.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/07/11 19:37:08

%% Initialize variables.
filename = 'C:\Users\terry\OneDrive\PhD\Xe Model 2019-1-03\run_10_SA\New_Xe_Model\Buildup_Trans_ORNL_TM_3464_Fig_26.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
buildup_t = dataArray{:, 1}*60*60;
buildup_p = dataArray{:, 2};
buildup_p(1) = 0;

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;