% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Dec-2018 00:01:02
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
                                                 


D_g = 2.37E-9;

%Thermophysical Properties
T_Mes = 928.15  %Temperature at which the physical properties of the fuel salt was measured. 1200 deg. F; ORNL-TM-0728, p. 8
%NBL Operation temperature on p. 100 or TM-728.

%Viscosity
FS_Mu_A = 4340;
FS_Mu_K = 0.084;
FS_Mu_MSRE = 0.007027 %17 lb/ft-hr in Pa-s; ORNL-TM-0728 p.8

%Density
FS_rho_A = 3.628;
FS_rho_B = 0.00066;
FS_rho_MSRE = 2082% kg/m^3. from 130 lb/ft^3. ORNL-TM-0728 p. 8




L_GS = 1.6; %ORNL-4069 p. 6 fig 4




N_FC_R1 = 12; %Number of fuel channel, C.F> ORNL-TM-0378
N_FC_R2 = 940;
N_FC_R3 = 108;
N_FC_R4 = 78;
N_FC_tot = 1128; %sum of all the regions




Q_strpr = 0.003155;

Q_tot = 0.07571;

R_gas = 8.314;

Sig_f = 0.15;

T_Salt = 900;
T_Salt_0 = 900;

U_FC_R1 = 0.607; %ORNL-TM-0378 p.14
U_FC_R2 = 0.183;
U_FC_R3 = 0.454;
U_FC_R4 = 0.250;




epsilon = 0.1;

eta_b = 1E-4%0.1;

eta_fs = 1.2E-4%0.12;

f_cv = 0.004;

gamma_i = 0.0293524;

gamma_te = 0.0322482;

gamma_xe = 0.00257324;

k_b = 1.3806E-23; %Bolzman's Constant


lambda_i = 2.9306070546251702E-5;

lambda_te = 0.036481430555786593;

lambda_xe = 2.0924e-05;

 phi0 = 3.98E+17;

%r_OOC = 0.1;

r_b = 0.000254;

r_fc = 0.79e-2 %EQUIVALENT RADIUS%0.01454;

r_gs = 0.01454;

r_xe = 2.16E-10;

sig_a_xe = 1.18E-22;



h_fc = 1.6; %63" from fig. 4 in ONRL-4069, p. 6


%Temperature distributions
%From ORNL-TM-0378 p.45 --- graphite
R_gr_m  = [ 0, 7.840134e-02, 7.979743e-02, 1.110706e-01,  ...
            1.725374e-01, 1.969467e-01, 2.502111e-01, 3.137128e-01, ...
            3.643293e-01, 4.295622e-01, 4.933898e-01, 5.427344e-01, ...
            5.979965e-01, 6.285161e-01, 6.302473e-01, 7.042308e-01]

T_gr_K =  [9.479114e+02, 9.471538e+02, 9.628461e+02, 9.660132e+02, ...
           9.685619e+02, 9.684143e+02, 9.666227e+02, 9.627852e+02, ...
           9.586270e+02, 9.516360e+02, 9.443291e+02, 9.384356e+02, ...
           9.306520e+02, 9.265643e+02, 9.234109e+02, 9.149254e+02]

%---fuel salt---
R_fs_m = [ 0, 4.113279e-02, 7.702932e-02, 7.987520e-02, ...
           1.227540e-01, 1.714875e-01, 2.634332e-01, 3.353781e-01, ...
           3.915383e-01, 4.722448e-01, 5.227244e-01, 5.732039e-01, ...
           6.092634e-01, 6.294641e-01, 6.311583e-01, 6.714634e-01, ...
           7.045715e-01,]

T_fs_K = [ 9.156575e+02, 9.155935e+02, 9.153718e+02, 9.309071e+02, ...
           9.327384e+02, 9.333500e+02, 9.322447e+02, 9.301849e+02, ...
           9.281185e+02, 9.244458e+02, 9.217463e+02, 9.190468e+02, ...
           9.170904e+02, 9.159159e+02, 9.131568e+02, 9.118330e+02, ...
           9.107427e+02,]

%effective radii of graphite regions (m). C.F> ORNL-TM-0378 p. 14
r_g_r1 = 3.78*2.54E-2;
r_g_r2 = 24.76*2.54E-2;
r_g_r3 = 26.10*2.54E-2;
r_g_r4 = 27.58*2.54E-2;


T_G_R_1_0 = mean(interp1(R_gr_m,T_gr_K, linspace(0,r_g_r1)))
T_G_R_2_0 = mean(interp1(R_gr_m,T_gr_K, linspace(r_g_r1,r_g_r2)))
T_G_R_3_0 = mean(interp1(R_gr_m,T_gr_K, linspace(r_g_r2,r_g_r3)))
T_G_R_4_0 = mean(interp1(R_gr_m,T_gr_K, linspace(r_g_r3,r_g_r4)))

T_FS_R_1_0 = mean(interp1(R_fs_m,T_fs_K, linspace(0,r_g_r1)))
T_FS_R_2_0 = mean(interp1(R_fs_m,T_fs_K, linspace(r_g_r1,r_g_r2)))
T_FS_R_3_0 = mean(interp1(R_fs_m,T_fs_K, linspace(r_g_r2,r_g_r3)))
T_FS_R_4_0 = mean(interp1(R_fs_m,T_fs_K, linspace(r_g_r3,r_g_r4)))

%INLET AND OUTLET TEMPERATURES. CF. ORNL-TM-0728 P.78
T_OUTLET = (1225 +458.67)*5/9
T_INLET = (1175 +458.67)*5/9
%FROM UH TO HX, T=OUTLET TEMP
T_UH_0 = T_OUTLET
T_P100_0 = T_OUTLET
T_FP_0 = T_OUTLET
T_P101_0 = T_OUTLET
%HX = AVERAGE OF INLET AND OUTLET TEMP
T_HX_0 = 0.5*(T_OUTLET + T_INLET)
%FROM HX TO LH, T=INLET TEMP
T_P102_0 = T_INLET
T_CA_0 = T_INLET
T_LH_0 = T_INLET


%%%%%%%%%%%% GRAPHITE FLUX %%%%%%%%%
%%Digitized form ORNL-TM-0378 p.23
phi_G_R = [ 0.0000,0.0296,0.0635,0.0748,0.0907,0.1180,0.1387,0.1631, ...
              0.1848,0.2130,0.2619,0.3090,0.3966,0.4851,0.5614,0.6264, ...
              0.6867,0.7093,0.7121,0.7281,0.7479]
          
phi_G_phi = [7.6111E+17,7.4815E+17,7.3889E+17,7.3333E+17, ...
             7.6852E+17,8.0741E+17,8.2407E+17,8.3148E+17, ...
             8.3333E+17,8.2593E+17,8.0000E+17,7.6111E+17, ...
             6.4815E+17,5.0556E+17,3.6852E+17,2.4259E+17, ...
             1.2037E+17,7.4070E+16,4.2590E+16,2.7780E+16,9.2600E+15]


phi_G_R_1 = mean(interp1(phi_G_R,phi_G_phi, linspace(0,r_g_r1)))
phi_G_R_2 = mean(interp1(phi_G_R,phi_G_phi, linspace(r_g_r1,r_g_r2)))
phi_G_R_3 = mean(interp1(phi_G_R,phi_G_phi, linspace(r_g_r2,r_g_r3)))
phi_G_R_4 = mean(interp1(phi_G_R,phi_G_phi, linspace(r_g_r3,r_g_r4)))

%phi_G_R_1 = 5.2053E17;
%phi_G_R_2 = 5.1130E17;
%phi_G_R_3 = 1.5775E17;
%phi_G_R_4 = 9.589E16;

%%%%%%%%
%phi_g_R_1_mult = phi_G_R_1 / phi0;
%phi_g_R_2_mult = phi_G_R_2 / phi0;
%phi_g_R_3_mult = phi_G_R_3 / phi0;
%phi_g_R_4_mult = phi_G_R_4 / phi0;
%%%%%%%%%%



%Surface tension correaltion in formation: A-BT
ST_A = 260
ST_B = 0.12

%Henry's Law coeffecient of temperature
%%From Watson, Evans, Grimes, 1962
%fit data using  f(x) = a*x^2 + b*x + c
%%C.F. Watson.m
%UB 1073 K
%LB 773 K
%Goodness of fit:
%  SSE: 1.218e-18
%  R-square: 0.9994
%  Adjusted R-square: 0.9983
%  RMSE: 1.103e-09
H_Xe_a = 5.713e-13;
H_Xe_b = -7.937e-10 ;
H_Xe_c =   2.809e-07 ; 

%Fuel salt mass at 900K

%t_DC = 0.02 %downcomer thickness
%A_DC = 0.1621 %downcomer cross-sectional area

%upper/lower head/plenum residence times.
t_up = 3.9 % seconds. taken from ORNL-TM-0728 p. 102
t_lp = 3.8
t_ooc = 8.1 %calculated by 25.2 -9.4-3.9-3.8

P_pump = 35420; %47.5 HP;  ORNL-TM-0728 P. 151

cubed_foot_to_cubed_meter = 0.02831685
V_Core_FS_0 = 25*cubed_foot_to_cubed_meter%25 ft^3 ORNL-TM-0728, p.102. 'core volume only'. between the graphite planes
%V_1_FC =  5.03E-4 %Fuel volume in 1 channel

%Volume of fuel salt in the various graphite regions
V_R1_0 = V_Core_FS_0 *N_FC_R1/N_FC_tot
V_R2_0 = V_Core_FS_0 *N_FC_R2/N_FC_tot
V_R3_0 = V_Core_FS_0 *N_FC_R3/N_FC_tot
V_R4_0 = V_Core_FS_0 *N_FC_R4/N_FC_tot

V_FP_0 = (0.9+3.2)*cubed_foot_to_cubed_meter
V_LH_0 = 10.0*cubed_foot_to_cubed_meter
V_UH_0 = 10.5*cubed_foot_to_cubed_meter
V_CA_0 = 9.7*cubed_foot_to_cubed_meter

V_HX_0 = 6.1*cubed_foot_to_cubed_meter
V_P100_0 = 2.1*cubed_foot_to_cubed_meter;
V_P101_0 = 0.8*cubed_foot_to_cubed_meter;
V_P102_0 = 2.2*cubed_foot_to_cubed_meter;
f = 2.2*cubed_foot_to_cubed_meter;
V_Tot_0 = V_FP_0 + V_LH_0 + V_UH_0 + V_CA_0 + V_R1_0 + V_R2_0 + V_R3_0 + V_R4_0 + V_HX_0 + V_P100_0 + V_P101_0 + V_P102_0;
V_IC = V_LH_0+V_UH_0+V_Core_FS_0 %25+10.5+10 cubic feet. C.F. ORNL-TM-0728 p. 102.  Using 'core', 'upper head', and 'lower head'


    
%VF_FP_0 = V_FP_0/ V_Tot_0;
%VF_MP1_0 = V_MP1 / V_Tot_0;
%VF_MP2_0 = V_MP2 / V_Tot_0;
%VF_DC_0 = V_DC / V_Tot_0;
%VF_R1_0 = V_R1 / V_Tot_0;
%VF_R2_0 = V_R2 / V_Tot_0;
%VF_R3_0 = V_R3 / V_Tot_0;
%VF_R4_0 = V_R4 / V_Tot_0;
%VF_HX_0 = V_HX / V_Tot_0;
%VF_P1_0 = V_P100 / V_Tot_0;
%VF_P2_0 = V_P10001 / V_Tot_0;
%VF_P3_0 = V_P10002 / V_Tot_0;

V_CV_0 = f_cv*V_IC;



%Cooling Annulus
T_CA = 635+273.15 %C.F. ORNL-TM-0728 p. 78
Re_CA = 25800 %C.F. ORNL-TM-0728 p. 93

Re_LH = 1E4 %lower heaed reynolds number
Re_UH = 1E4 %upper heaed reynolds number

r_pipe = (5E-2*2.54)/2;
A_pipe = pi*r_pipe^2;

%heat exchanger
HX_N_Tubes = 159;
HX_r_Tube = ((0.5-0.042)/2)*2.54E-2; %ORNL-TM-2098 p. 9
HX_XS = HX_N_Tubes*(pi*HX_r_Tube^2); %heat exchanger cross-sectional flow area


P_sys = 344738 %50 PSI; from ORNL-TM-0728 p. 78

%REACTIVITY COEFFECIENTS FROM P. 54 of ORNL-TM-3464
%%NB: units in cm^-3 so make sure you multiply the number densities by 1E-6
alpha_FS = 0.517E-16 %
alpha_G_R1 = 0.334E-17
alpha_G_R2 = 0.699E-17
alpha_G_R3 = 0.669E-17
alpha_G_R4 = 0.791E-18

%experimental end time
t_exp_end = 144100;